---
name: appdaemon-predbat
version: 1.1.0
slug: appdaemon-predbat
description: Predbat pre-install in AppDaemon
url: https://github.com/springfall2008/appdaemon-predbat
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:5051]
arch:
  - aarch64
  - amd64
  - armv7
init: false
homeassistant_api: true
uart: true
ports:
  5051/tcp: 5051
ports_description:
  5051/tcp: AppDaemon
map:
  - addon_config:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl
options:
  system_packages: []
  python_packages: []
  init_commands: []
  initial_download: ["https://raw.githubusercontent.com/springfall2008/batpred/v7.16.7/apps/predbat/predbat.py", "https://raw.githubusercontent.com/springfall2008/batpred/v7.16.7/apps/predbat/config/apps.yaml"]
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  system_packages:
    - str
  python_packages:
    - str
  init_commands:
    - str
  initial_download:
    - str
